//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectIris.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.accounts = new HashSet<account>();
        }
    
        public int id { get; set; }
        public string clientidnumber { get; set; }
        public string iriscode { get; set; }
        public string title { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string ssnumber { get; set; }
        public System.DateTime dateofbirth { get; set; }
        public string maritalstatus { get; set; }
        public string employment { get; set; }
        public string emailaddress { get; set; }
        public string residentaddress { get; set; }
        public string country { get; set; }
        public string postcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account> accounts { get; set; }
    }
}
