//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectIris.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees_log
    {
        public employees_log() { }

        public employees_log(int id, DateTime datecreated, string employeeid, string message)
        {
            this.id = id;
            this.datecreated = datecreated;
            this.employeeid = employeeid;
            this.message = message;
        }

        public int id { get; set; }
        public System.DateTime datecreated { get; set; }
        public string employeeid { get; set; }
        public string message { get; set; }
    }
}
