//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectIris.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchases_log
    {
        public purchases_log() { }

        public purchases_log(int Id, DateTime dateofpurchase, string employeeid, decimal amount, string accountnumber, string message)
        {
            this.Id = Id;
            this.dateofpurchase = dateofpurchase;
            this.employeeid = employeeid;
            this.amount = amount;
            this.accountnumber = accountnumber;
            this.message = message;
        }

        public int Id { get; set; }
        public System.DateTime dateofpurchase { get; set; }
        public string employeeid { get; set; }
        public decimal amount { get; set; }
        public string accountnumber { get; set; }
        public string message { get; set; }
    }
}
